In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.preprocessing import MinMaxScaler 
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_squared_error, r2_score

In [9]:
np.random.seed(0)
x = 2 * np.random.rand(100,1)
y = 4 + 3 * x + np.random.randn(100,1)
data = pd.DataFrame({
    
    'x' : x.flatten(),
    'y' : y.flatten()

})

x_traib, x_test, y_train, y_test = train_test_split(x,y, test_size)

           x         y
0   1.097627  6.127731
1   1.430379  9.191963
2   1.205527  8.082243
3   1.089766  5.733055
4   0.847310  8.030181
..       ...       ...
95  0.366383  5.780743
96  1.173026  6.715668
97  0.040215  3.431095
98  1.657880  8.518108
99  0.009391  4.045652

[100 rows x 2 columns]